language: php

before_script:
  - composer self-update -n
  - composer install -o -n

php:
  - 5.6
  - 5.5
  - 5.4

script:
  - vendor/bin/phpcs --standard=PSR2 source/
  - vendor/bin/phpunit --testdox
