language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 7
  - hhvm 
  
matrix:
  allow_failures:
    - php: hhvm
    - php: 7

before_script:
  - composer self-update -n
  - composer install -o -n

script:
    - composer test
    - composer checkstyle
