language: php

env:
  secure: "VOzlNNsDYKshZOOSRE8sdmJlETCcXKnloEC3NrYFCljsgiiFDRwhHiaFhOsNz1ZNd8zbjlooKx5JXox5Q6J6cKKm2CdpchakPzg4/V7kdm6zeonLtPa3qliTvUcfcuSslq6Yrxb47Z4XX6i9scprVL20bjOSLj4MdEsVT/Fj3NqxDQ3SoqgR3effPWvCHM848FP7Y6UtoVZ7kJh7swz9R3SJXfIdc/Uk4sUWGs5tpOt347zZstIgt2GMABNyMExrDAVh9rpjBeGO8aRQfZQ6tjVbAAo/kW8/LcjS1YzzMRXs+OaDrJEZdp7jgfIxFu4U5ACIg3WccgDWMYSZmrEhW1PGfVRFonDdYF7LitkRij9zqlfAI8MYah3EhooDfi6LUOsNPS+t9RFALxiMdje+xQT6xsPeqGC3vIJsa3tcEn49RjncFdpMTNdxibYLuECIHXK9YG8VYsHAwm6TFrIMGMCi/H+vxUmD7EoGaKhM9q4zo2Ejr70+xICX8m6hgEVR10nmUCR/cuRrlC4TGn8p9nFLQxy5WW1Pt0fkwPii97jZKAR1pxaII4c3NCPST9jTDkpF1mkqcbOyW6az0jwdFpNEVK997LY1P3uu/Eri0TNefxtm7t9cNbuG47N18EYQrr021BOJyvzZjzlNCbMYWyIGFtPpBhAW1nEUSnPR1wI="

cache:
  directories:
  - $HOME/.composer/cache

git:
  depth: 10

php:
- 5.6
- 5.5
- 5.4
- 7
- hhvm

matrix:
  allow_failures:
  - php: hhvm

before_script:
- composer config --global github-oauth.github.com $GITHUB_OAUTH_TOKEN
- composer self-update --no-interaction --no-progress
- composer install --no-interaction --no-progress --prefer-dist

script:
- vendor/bin/phpunit
